---
<<<<<<< HEAD
- name: update web, nfs 
  hosts: webservers, nfs 
=======
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
>>>>>>> b57681eab1b845f3ca96f158886d5797704cfb45
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

<<<<<<< HEAD
- name: update lb, db
  hosts: lb, db
=======
- name: update LB server
  hosts: lb
>>>>>>> b57681eab1b845f3ca96f158886d5797704cfb45
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

   
  